services:
  app:
    build:
      context: .
      args:
        # This passes the Clerk publishable key from your .env file into the Dockerfile during the build.
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    image: your-username/my-next-app
    # This loads all variables from your .env file into the container at runtime.
    env_file:
      - ./.env
    # This maps port 3000 on your local machine to port 3000 inside the container.
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    # Use the official PostgreSQL image from Docker Hub
    image: postgres:16-alpine
    # Always restart the container if it stops, for example, after a system reboot.
    restart: always
    # Load database credentials from your .env file for better security.
    env_file:
      - ./.env
    # Map port 5432 on your local machine to port 5432 in the container
    ports:
      - '5432:5432'
    # Persist data even if the container is removed and recreated.
    volumes:
      - postgres_data:/var/lib/postgresql/data

# 3. Define the named volume for persistent database storage
volumes:
  postgres_data: